#!/usr/bin/env bash

if [[ -z "$QUERY_STRING" ]]
then
    QUERY_STRING="$@"
fi

gitroot="$(pwd | grep -iPo '^.+/wallpapers(?=(/|$))')"

# easy access to those url encode/decode functions
export PATH="${PATH}:$gitroot/.internals/cgi-bin/"

echo "Content-type: text/html"
echo
echo "<title>Test CGI</title>"
echo "<p>Hello World!</p>"
echo "<br>"
echo "<p>whoami: $(whoami)</p>"
echo "<p>query string: $QUERY_STRING</p>"
echo "<p>write test: $(echo "$QUERY_STRING" >> "$gitroot/.internals/cgi-bin/trim_args.log")</p>"
echo "<p>args logged? $?<p>"
echo "<p>log read test: $(cat "$gitroot/.internals/cgi-bin/trim_args.log")</p>"
echo "<p>file logged? $?<p>"

# IFS='&=' read -ra parm <<<"$QUERY_STRING"

declare -A param
while IFS='=' read -r -d '&' key value && [[ -n "$key" ]]; do
    # param["$key"]=$value
    # param["$key"]=$(echo $value | sed 's/\(+\|%20\)/ /g')
    param["$key"]="$(echo "$value" | urldecode | sed 's/+/ /g')"
done <<<"${QUERY_STRING}&"


echo "<hr>"
echo "<p>decoded query params:</p>"
echo "decoded query params:" >> "$gitroot/.internals/cgi-bin/trim_args.log"

for i in "${!param[@]}"
do
    demo="$i: ${param[$i]}"
    echo "<p>$demo</p>"
    echo "$demo" >> "$gitroot/.internals/cgi-bin/trim_args.log"
done

# TODO validate with a simple provided token here
# nothing fancy

echo "<hr>"

# git config --global --add safe.directory /media/content/Wallpapers
fileExt="${param[sourcename]##*.}"

sourcePath="$gitroot${param[dirname]}/${param[sourcename]}"
thumbSource="$gitroot/.internals/thumbnails${param[dirname]}/${param[sourcename]}"
# attrib

echo "<p>pwd: $(pwd)</p>"
echo "<p>gitroot: $gitroot</p>"
echo "<p>sourcePath: $sourcePath</p>"
echo "<p>thumbSource: $thumbSource</p>"

centertrim "$sourcePath" "$sourcePath"
rm "$thumbSource"
